import './globals.css'
import { Inter } from 'next/font/google'
import Header from './hf/header'
import Footer from './hf/footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Best Look',
  description: 'Generated by Moaz007Malik',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
      <main>
      </main>
        {children}<Footer/>
        </body>
    </html>
  )
}
